"""empty message

Revision ID: 0696f2176b72
Revises: 415682ee0bbb
Create Date: 2020-01-28 14:34:49.116353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0696f2176b72'
down_revision = '415682ee0bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reddit_comments', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('reddit_comments_author_fkey', 'reddit_comments', type_='foreignkey')
    op.create_foreign_key(None, 'reddit_comments', 'reddit_users', ['author_id'], ['id'])
    op.drop_column('reddit_comments', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_comments', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reddit_comments', type_='foreignkey')
    op.create_foreign_key('reddit_comments_author_fkey', 'reddit_comments', 'reddit_users', ['author'], ['id'])
    op.alter_column('reddit_comments', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
