"""empty message

Revision ID: 1461d126fa56
Revises: 3451c488e304
Create Date: 2020-03-03 11:12:17.326023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1461d126fa56'
down_revision = '3451c488e304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('karma', sa.Integer(), nullable=True),
    sa.Column('age', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('eligible', sa.JSON(), nullable=True),
    sa.Column('winners', sa.JSON(), nullable=True),
    sa.Column('violators', sa.JSON(), nullable=True),
    sa.Column('not_entering', sa.JSON(), nullable=True),
    sa.Column('thread', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reddit_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('entering', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['reddit_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steam_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_comment_id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('public_profile', sa.Boolean(), nullable=True),
    sa.Column('existent', sa.Boolean(), nullable=True),
    sa.Column('games_visible', sa.Boolean(), nullable=True),
    sa.Column('games_count', sa.Integer(), nullable=True),
    sa.Column('not_scrapped', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reddit_comment_id'], ['reddit_comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steam_users')
    op.drop_table('reddit_comments')
    op.drop_table('results')
    op.drop_table('reddit_users')
    # ### end Alembic commands ###
