"""empty message

Revision ID: 1a78da081131
Revises: 5b7889b3c6fd
Create Date: 2020-02-09 14:27:16.715057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a78da081131'
down_revision = '5b7889b3c6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('not_entering', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('results', sa.Column('thread', sa.String(), nullable=True))
    op.add_column('results', sa.Column('violators', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'violators')
    op.drop_column('results', 'thread')
    op.drop_column('results', 'not_entering')
    # ### end Alembic commands ###
