"""empty message

Revision ID: 28b4b9371f54
Revises: e5e4171f6448
Create Date: 2020-02-05 13:07:07.340080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b4b9371f54'
down_revision = 'e5e4171f6448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steam_users', sa.Column('games_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steam_users', 'games_count')
    # ### end Alembic commands ###
