"""empty message

Revision ID: 3451c488e304
Revises: 9ac4df52f96c
Create Date: 2020-03-02 22:17:16.538434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3451c488e304'
down_revision = '9ac4df52f96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steam_users', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steam_users', 'url')
    # ### end Alembic commands ###
