"""empty message

Revision ID: 588d242405c9
Revises: 28b4b9371f54
Create Date: 2020-02-05 19:09:41.210783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588d242405c9'
down_revision = '28b4b9371f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steam_users', sa.Column('public_profile', sa.Boolean(), nullable=True))
    op.drop_column('steam_users', 'public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steam_users', sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('steam_users', 'public_profile')
    # ### end Alembic commands ###
