"""empty message

Revision ID: 5b7889b3c6fd
Revises: 588d242405c9
Create Date: 2020-02-08 10:10:32.796306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7889b3c6fd'
down_revision = '588d242405c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('eligible', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('winners', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
