"""empty message

Revision ID: 6a50d5d39b0f
Revises: 157df3b75cc9
Create Date: 2020-02-14 13:19:21.441238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a50d5d39b0f'
down_revision = '157df3b75cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_users', sa.Column('age', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_users', 'age')
    # ### end Alembic commands ###
