"""empty message

Revision ID: df1be8d55773
Revises: 1a78da081131
Create Date: 2020-02-11 13:16:29.914679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1be8d55773'
down_revision = '1a78da081131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('karma', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('eligible', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('winners', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('violators', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('not_entering', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('thread', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reddit_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('entering', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['reddit_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steam_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_comment_id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('public_profile', sa.Boolean(), nullable=True),
    sa.Column('existent', sa.Boolean(), nullable=True),
    sa.Column('games_visible', sa.Boolean(), nullable=True),
    sa.Column('games_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reddit_comment_id'], ['reddit_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steam_users')
    op.drop_table('reddit_comments')
    op.drop_table('results')
    op.drop_table('reddit_users')
    # ### end Alembic commands ###
