"""empty message

Revision ID: e5e4171f6448
Revises: a899b99da327
Create Date: 2020-02-03 14:47:12.950120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e4171f6448'
down_revision = 'a899b99da327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_comments', sa.Column('body', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_comments', 'body')
    # ### end Alembic commands ###
